import type { Metadata } from "next"
import "./globals.css"
import Providers from "@/app/providers"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="ru">
            <body className="min-h-screen bg-gray-50 text-gray-900">{children}</body>
            <Providers>
                <main className="mx-auto max-w-md p-6">{children}</main>
            </Providers>
        </html>
    )
}
